CREATE TABLE [User](
UserId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Name NVARCHAR(200) NOT NULL,-- generalized
Address NVARCHAR(300) NOT NULL,-- generalized
DOB DATE NOT NULL,
PhoneNumber NVARCHAR(20) NOT NULL-- generalized
);

CREATE TABLE Passport(
PassportId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
PassportNumber NVARCHAR(50) NOT NULL,--perhaps same number can be renewed with a new expiration date
ExpirationDate DATE NOT NULL,
Address NVARCHAR(300) NOT NULL,-- generalized
UserID INT FOREIGN KEY REFERENCES [User](UserId) NOT NULL
);

CREATE TABLE Trip(
TripId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
StartDate DATE NOT NULL,
EndDate DATE NOT NULL,
StartingDest NVARCHAR(300) NOT NULL,
EndingDest NVARCHAR(300) NOT NULL,
TravelMode NVARCHAR(20) NOT NULL,
Budget DECIMAL(10,2) NOT NULL,
UserID INT FOREIGN KEY REFERENCES [User](UserId) NOT NULL
);

CREATE TABLE UserTrip(
UserTripId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
TripId INT FOREIGN KEY REFERENCES [Trip](TripID) NOT NULL,
UserID INT FOREIGN KEY REFERENCES [User](UserId) NOT NULL
);

CREATE TABLE Hotel(
ReservationId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
CostPerNight DECIMAL(10,2) NOT NULL,
CheckinDate DATE NOT NULL,
CheckoutDate DATE NOT NULL,
Address NVARCHAR(300) NOT NULL,-- generalized
PhoneNumber NVARCHAR(20) NOT NULL,-- generalized
TripID INT FOREIGN KEY REFERENCES Trip(TripID) NOT NULL
);
